language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t christopherschroer/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true christopherschroer/react-test npm test

after_success:
    - docker build -t christopherschroer/multi-client ./client
    - docker build -t christopherschroer/multi-nginx ./nginx
    - docker build -t christopherschroer/multi-server ./server
    - docker build -t christopherschroer/multi-worker ./worker
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push christopherschroer/multi-client
    - docker push christopherschroer/multi-nginx
    - docker push christopherschroer/multi-server
    - docker push christopherschroer/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-587014798775
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY